---
title: "Geography 176A"
author: "[Mike Johnson](https://github.com/mikejohnson51)"
date: "Summer Session B"
mail: "jmj00@ucsb.edu"
github: "mikejohnson51"
class_name: "Geography 176A"
home: ""
output:
  mikedown::ucsb:
    toc: FALSE
    number_sections: FALSE
    code_folding: "hide"
subtitle: 'Syllabus'
---

<br><br>

<style>
h1 {
  size: 48px;
  text-align:center;
}

h3 {
  size: 32px;
  text-align:center;
}
</style>

<header class="masthead">
  <div id="particles-js"></div>
</header>

<!-- scripts -->
<script src="js/particles.js"></script>
<script src="js/appHome.js"></script>

<br><br><br><br>

> **Geography 176A** seeks to provide a comprehensive overview of Geographic Information Systems and Science. Topics span the nature of geographic information and the procedures for operating GIS. Labs provide hands-on experience with spatial data. The goal of 176A is a expousre to the techniques, mehtods, and opportunites in geoinformatics.

<br><br>

# `r icon::fa_home()` [**Lectures**](index.html) --- `r icon::fa_desktop()` [**Lab Activites**](labs-home.html) 
### **Dates:** August 3^rd^, 2020 --- September 12^th^, 2020
### **Lecture:**  MTWR 12:30 - 1:35pm  --- **Labs:** W or R 3:30 - 4:50pm 

***

<br><br>

### Instructors

| Name        | Role           | Email  | Office Hours |
| ----------- |:--------------:| :------:| :------------:|
| Mike Johnson | Instructor | jmj00@ucsb.edu | TBD |
| Jiwon Baik | Teaching Assistant      |  jiwon.baik@ucsb.edu  | TBD |
| Matthew Feliciano | Teaching Assistant      | feliciano@ucsb.edu | TBD |
| Ryan Erikson  | Instructional Assistant      |    ryanerickson@ucsb.edu | NA |

***

<br><br>


### Course Structure

**Prerequisite**: Geography 12  
**Credit hours**: 4 units  
**Course website**: [https://github.com/mikejohnson51/geog176A](https://github.com/mikejohnson51/geog176A)  

The class meets 4 times a week for a 65-minute discussion (M-R). Lecture material will be a mix of live coding and presentation depending on the daily topic. All work will be done in R - teaching the basics of data wrangling, manipulation, visualization and analysis for spatial data. By the end of this course you will feel comfortable generating reports and visualizations of varied data type, and communicating across printed and web-based platforms. More importantly you will understand vector, raster and tabular data and the basics for operating on them in a coding environment. You will be comfortable maintaining and contributing to Github repositories, and generating reproducible, sharable reports that communicate your analysis. The general map for this course can be seen below:

```{r, echo=FALSE}
htmltools::includeHTML("../resources/timeline.html")
```

### Software and Programing Language

In this course you will use [R](https://www.r-project.org/) to do your work. `R` is an open source programming environment which you will need to interact with through the [RStudio IDE](https://rstudio.com/). Your projects and code will be turned into through [GitHub](https://github.com/) as [Rmarkdown]() reports. Through the course you will build an online portfolio hosted as a static website using a personal GitHub account.

Some might wonder why we are not using ArcMap in an introductory GIS course as it could be argued as the de-facto graphical GIS interface. My reasoning is that:

1. learning GIS in a coding environment forces you to focus on the data and the processes that are sometimes obscured - if not hidden - in commercial GIS environments.
2. R and everything is you will learn in the course is free. That means you wont be out of luck when you graduate.
2, Learning the design and architecture of your computer, and how it handles files and projects, is a critical skill set that is easy to neglect in self contained environments.
3. The role of programming and "data science" is becoming increasingly prominent - if not necessary - in current GIS positions. 
4. R lends itself to reproducible analysis in a way graphical GIS platforms like ArcMap and QGIS cannot, which is foundational to sound science in or out of university
5. By the time you leave UCSB, and take the complete 176 series, you will have used ArcMap sufficiently and you will be able to tell employers that you know a programming and graphical interface for spatial analysis. We touch more on these reasons in the first week of class.

***

<br><br><br>

### Grades

A total of 1,000 points can be obtained in this course. Points are cumulative and the overall breakdown of assignments and types of work are given below:

<div class = "row">
  
<div class = "col-md-6">
### Labs (60%)
Each week will have a 90 minute lab section focused on introducing applied topics such as data visualization, cartography, and applying code to practical problems together. With each lab, there will be a lab activity. These will be introduced in Mondays lecture, and will be due the following Sunday at 5:00pm. 
</div>

<div class = "col-md-6">
### Daily Assignments (40%)

#### Exersises
Each day (of class) will include a daily assignment due the following day. These should take ~30 minutes and are either coding or reading assignments. They will be graded pass/fail based on whether an honest attempt was made. These are intended to encourage you to code each day, and to solidify the concepts learned in an applied way. There will be 22 opportunities to complete an assignment. Each is worth 20 points and 20 of them are required. The remaining two will count as extra credit if completed, or as a free "opps" pass for days you have other obligations/commitments.
</div>
</div>

<div class = "row">
<div class = "col-md-6">
</div>
  
<div class = "col-md-6">
#### Readings
Everything in this course from the software we use, to the texts we read are **free**! You will not need to purchase anything.
</div>
</div>

<br><br><br>

|  Activity           | Topic          | Points | Assigned     | Due Date    |
| ----------- |:--------------:| ------:| ------------:|------------:|
| Lab 01            | Version control and Reproducible reports | 100 | August 3^rd^ | August 9^th^ |
| Lab 02            | Data Visualization & Wrangling | 100 | August 10^th^| August 16^th^|
| Lab 03            | Object Operations | 100 | August 17^th^| August 23^th^|
| Lab 04            | Field Operations  | 100 | August 24^th^| August 30^th^|
| Lab 05            | Working with Time | 100 | August 31^st^| August 6^th^ |
| Lab 06            | Final Practical | 100 | August 7^th^ | August 13^th^|
| Final             | Final Portfolio w/ CV | 100 |              | August 13^th^|
| Daily Exercises   |  | 400 |              |              |
| Total:            |  | 1,000 |              |              |

***

<br><br><br>

### Workload

A four-credit course will require, for the average undergraduate student, twelve hours of academic work per week, averaged over a 10 week term. Since this is a summer course we have to cover these 120 hours over 6 weeks (~20 hours a week). Generally I don't think you will spend this long but should anticipate budgeting the following each week:

- Lecture: 4 hours
- Lab Section: 1.5 hour
- Daily Exercises: 30 min * 4 = 2 hours
- Lab Activity: 2 - 3 hours 

**Total:** ~10-12 hours a week

### My promise

This class will have a steep learning curve. Myself and the TAs will do everything we can to help you along. If you stick with the course and do the work (particularly the daily assignments!), you will get a good grade, learn a lot, and be prepared to serve as a spatial data scientist.




